project:
  type: website
  output-dir: docs

website:
  title: "Matthew Andreotta"
  site-url: https://matt-lab.github.io
  twitter-card:
    creator: "@MattAndreotta"
    image: "/assets/images/network.jpg"
  open-graph: true
  description: "Matthew Andreotta | Postdoctoral Fellow | CSIRO"
  google-analytics:
    tracking-id: "G-36XVQ86SSB"
    anonymize-ip: true
    storage: none
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - presentations.qmd
      - collaborators.qmd
    right:
      - href: assets/cv/cv.pdf
        text: Academic CV
format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true

execute:
  echo: false
  warning: false
  error: false




