project:
  type: website
  output-dir: docs

website:
  title: "Matthew Andreotta"
  site-url: https://matt-lab.github.io
  twitter-card:
    creator: "@MattAndreotta"
    image: "/assets/images/network.jpg"
  open-graph: true
  description: "Matthew Andreotta | Postdoctoral Fellow | CSIRO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - presentations.qmd
      - collaborators.qmd
    right:
      - href: assets/cv-industry/cv.pdf
        text: Industry CV
      - href: assets/cv-academic/cv.pdf
        text: Academic CV
format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true
    link-external-newwindow: true

execute:
  echo: false
  warning: false
  error: false




